from pathlib import Path
import re

path = Path('index.html')
html = path.read_text(encoding='utf-8')

css_marker = '/* SERVICES_V2_ANIMATED */'
css = r'''/* SERVICES_V2_ANIMATED */
.services-showcase{position:relative;overflow:hidden}.services-stage{position:relative;isolation:isolate;min-height:610px;display:flex;align-items:center;justify-content:flex-end}.services-panel{position:relative;z-index:3;width:min(1080px,86%);min-height:500px;border:1px solid rgba(18,23,27,.08);border-radius:42px;background:linear-gradient(145deg,rgba(255,253,249,.99),rgba(248,246,241,.99));box-shadow:0 34px 70px rgba(50,59,65,.13),inset 0 1px 0 rgba(255,255,255,.92);display:grid;grid-template-columns:repeat(2,minmax(0,1fr));overflow:hidden;margin-right:4px}.services-panel:before{content:"";position:absolute;right:-130px;top:-160px;width:390px;height:390px;border:1.5px solid rgba(216,92,43,.78);border-radius:50%;pointer-events:none}.services-panel:after{content:"✦";position:absolute;right:42px;bottom:28px;color:var(--orange);font-size:42px;font-weight:200}.service-offer{position:relative;min-width:0;padding:62px 54px 52px}.service-offer+.service-offer{border-left:1px solid var(--line)}.service-icon{width:62px;height:62px;border-radius:20px;background:#fcfaf6;box-shadow:0 7px 18px rgba(34,43,49,.11),inset 0 1px 0 rgba(255,255,255,.9);display:grid;place-items:center;color:var(--orange);margin-bottom:30px}.service-icon svg{width:32px;height:32px;stroke:currentColor;fill:none;stroke-width:1.7}.service-offer h3{font-family:var(--u);font-size:32px;font-weight:400;letter-spacing:-.04em;margin:0 0 14px;text-transform:uppercase}.service-desc{font-size:18px;line-height:1.45;color:#4f5960;margin:0 0 24px}.service-pills{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 28px}.service-pill{display:inline-flex;align-items:center;gap:9px;border-radius:999px;padding:10px 15px;background:rgba(216,92,43,.1);color:var(--orange);font-size:13px;font-weight:600;white-space:nowrap}.service-result{padding-top:22px;border-top:1px solid var(--line);font-size:16px;line-height:1.45}.service-result small{display:block;color:var(--muted);font-size:10px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:7px}.service-result b{font-size:19px;font-weight:500}.service-result em{font-style:normal;color:var(--orange)}.services-decor{position:absolute;z-index:4;pointer-events:none;user-select:none;width:min(560px,45vw);height:auto;left:-95px;bottom:-82px;max-width:none;filter:drop-shadow(0 25px 38px rgba(48,46,41,.08))}.services-decor-wind{z-index:2;opacity:.32;clip-path:polygon(0 0,58% 0,56% 42%,100% 67%,100% 100%,0 100%);animation:servicesHairWind 7s ease-in-out infinite;transform-origin:28% 72%;filter:saturate(1.04)}@keyframes servicesHairWind{0%,100%{transform:translate3d(-4px,3px,0) rotate(-.25deg) scale(1.015)}50%{transform:translate3d(15px,-5px,0) rotate(.35deg) scale(1.025)}}
@media(max-width:640px){.services-stage{min-height:auto;display:block;padding-top:44px}.services-panel{width:100%;min-height:0;border-radius:28px;grid-template-columns:1fr;margin:0;overflow:hidden}.services-panel:before{width:210px;height:210px;right:-96px;top:-104px}.services-panel:after{right:20px;bottom:16px;font-size:28px}.service-offer{padding:34px 22px 30px 58px}.service-offer+.service-offer{border-left:0;border-top:1px solid var(--line)}.service-icon{width:50px;height:50px;border-radius:16px;margin-bottom:21px}.service-icon svg{width:26px;height:26px}.service-offer h3{font-size:25px}.service-desc{font-size:15px;margin-bottom:18px}.service-pills{gap:7px;margin-bottom:20px}.service-pill{font-size:11px;padding:8px 10px}.service-result{padding-top:17px;font-size:14px}.service-result b{font-size:16px}.services-decor{width:320px;left:-127px;bottom:auto;top:126px;z-index:4}.services-decor-wind{z-index:2;opacity:.28;animation-duration:6.5s}}
@media(max-width:360px){.service-offer{padding-left:52px;padding-right:17px}.service-pill{white-space:normal}.services-decor{width:292px;left:-120px}}
@media(prefers-reduced-motion:reduce){.services-decor-wind{animation:none;display:none}}
'''

if css_marker not in html:
    html = html.replace('</style>', css + '</style>', 1)

new_section = r'''<section class="section services-showcase" id="services"><div class="shell"><div class="section-head"><h2 class="section-title">УСЛУГИ</h2><span class="section-index">01 / 04</span></div><div class="services-stage"><img class="services-decor services-decor-base" src="assets/services-decor.webp" alt="" aria-hidden="true"><img class="services-decor services-decor-wind" src="assets/services-decor.webp" alt="" aria-hidden="true"><div class="services-panel"><article class="service-offer"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="18"/><path d="M6 24h36M24 6c5 5 7 11 7 18s-2 13-7 18M24 6c-5 5-7 11-7 18s2 13 7 18"/></svg></div><h3>Сайты</h3><p class="service-desc">Одностраничники / лендинги с контактами</p><div class="service-pills"><span class="service-pill">◷ от 3 дней</span><span class="service-pill">₽ от 10 000 рублей</span></div><div class="service-result"><small>Результат</small><b>готовый сайт на платформе <em>github.io</em></b></div></article><article class="service-offer"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><rect x="7" y="9" width="34" height="24" rx="1"/><path d="M24 33v9M15 42h18M12 5v4M36 5v4"/></svg></div><h3>Презентации</h3><p class="service-desc">Презентации, брендбуки, фирменный стиль</p><div class="service-result"><small>Результат</small><b>презентация в <em>PPTX</em> и в <em>PDF</em></b></div><div class="service-pills" style="margin-top:24px;margin-bottom:0"><span class="service-pill">ϟ доступна опция день в день</span><span class="service-pill">₽ от 5 000 рублей</span></div></article></div></div></div></section>'''

pattern = re.compile(r'<section class="section" id="services">.*?</section>')
if not pattern.search(html):
    pattern = re.compile(r'<section class="section services-showcase" id="services">.*?</section>')
html, count = pattern.subn(new_section, html, count=1)
if count != 1:
    raise SystemExit(f'Could not replace services section; matches={count}')

path.write_text(html, encoding='utf-8')
print('services section updated')
